/**
 * @Date               : February 15, 2021
 * @Description        : controller class that stores Strings
 * @Author             : Heidi Tang (heitang@deloitte.com)
**/
public without sharing class N4LStringConstants {

    public static final String PROFILE_N4LADMIN = 'N4L System Administrator';
    public static final String AUTHORITY_MANAGECONTACT = 'manage contacts';
    public static final String AUTHORITY_NOMINATOR = 'authority nominator';
    public static final String ROLE_PRINCIPAL = 'principal';
    public static final String ROLE_ITLEAD = 'it lead';
    public static final String ICTPROVIDER_RELATION_PRIMARY = 'Primary / Contracted';    
    public static final String ICTPROVIDER_STATUS_CURRENT = 'Current';    

    // objects and fields
    public static final String OBJFIELD_ACRELATION = 'AccountContactRelation';
    public static final String OBJFIELD_CONTACT = 'Contact';

    public static final String OBJFIELD_ACRELATION_AUTHORITY = 'Authority__c';
    public static final String OBJFIELD_ACRELATION_ROLES = 'Roles';
    public static final String OBJFIELD_CONTACT_SYSTEMACCESSIBLE = 'System_Accessible__c';

    // record types
    public static final String ACCOUNT_RECTYPE_SCHOOL = 'School';
}